import { StyleSheet } from "react-native";
import { Tokens } from "@/theme";

export const createStyles = (tokens: Tokens) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: tokens.colors.surface,
    },
    label: {
      fontSize: 16,
      fontWeight: "600",
      marginBottom: 8,
      color: tokens.colors.foreground,
    },
    selectInput: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: tokens.colors.borderStrong,
      borderRadius: 8,
      padding: 12,
      backgroundColor: tokens.colors.surface,
    },
    selectText: {
      fontSize: 16,
      color: tokens.colors.foreground,
    },
    mapButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: tokens.colors.primary,
      borderRadius: 8,
      padding: 12,
      backgroundColor: tokens.colors.surface,
    },
    mapButtonText: {
      marginLeft: 8,
      fontSize: 16,
      color: tokens.colors.primary,
    },
    imageButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: tokens.colors.primary,
      borderRadius: 8,
      padding: 12,
      backgroundColor: tokens.colors.surface,
    },
    imageButtonText: {
      marginLeft: 8,
      fontSize: 16,
      color: tokens.colors.primary,
    },
    addServiceButton: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: "#3b82f6",
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
    },
    addServiceButtonText: {
      color: "#fff",
      fontSize: 14,
      fontWeight: "600",
      marginLeft: 4,
    },
    serviceIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: tokens.colors.primaryMuted,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 1,
      borderColor: tokens.palette.brand[200],
    },
    requiredText: {
      color: tokens.colors.error,
      fontSize: 16,
    },
    errorInput: {
      borderColor: tokens.colors.error,
    },
    errorText: {
      color: tokens.colors.error,
    },
    removeServiceButton: {
      padding: 4,
      marginLeft: 4,
    },
    priceTypeContainer: {
      flexDirection: "row",
      backgroundColor: tokens.colors.surfaceMuted,
      borderRadius: 8,
      padding: 2,
      borderWidth: 1,
      borderColor: tokens.palette.gray[200],
    },
    priceTypeButton: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 6,
      gap: 6,
    },
    priceTypeButtonActive: {
      backgroundColor: tokens.colors.primary,
      shadowColor: tokens.colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
    priceTypeButtonText: {
      fontSize: 13,
      color: tokens.colors.muted,
      fontWeight: "500",
    },
    priceTypeButtonTextActive: {
      color: tokens.colors.surface,
    },
    submitButton: {
      backgroundColor: tokens.colors.primary,
      paddingVertical: 16,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 0,
    },
    submitButtonText: {
      color: tokens.colors.surface,
      fontSize: 16,
      fontWeight: "600",
    },
    modalContainer: {
      flex: 1,
      backgroundColor: "rgba(0,0,0,0.5)",
      justifyContent: "flex-end",
    },
    modalContent: {
      backgroundColor: "#fff",
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      padding: 16,
      maxHeight: "80%",
    },
    searchContainer: {
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#ddd",
      borderRadius: 8,
      paddingHorizontal: 12,
      marginBottom: 16,
    },
    searchInput: {
      flex: 1,
      paddingVertical: 12,
      fontSize: 16,
    },
    cityItem: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: "#eee",
    },
    cityItemText: {
      fontSize: 16,
      color: "#333",
    },
    dropdownContainer: {
      position: "absolute",
      top: "100%",
      left: 0,
      right: 0,
      backgroundColor: "#fff",
      borderRadius: 12,
      borderWidth: 1,
      borderColor: "#e0e0e0",
      marginTop: 4,
      maxHeight: 300,
      zIndex: 1000,
      elevation: 5,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
    },
    searchInputContainer: {
      flexDirection: "row",
      alignItems: "center",
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: "#f0f0f0",
    },
    searchIcon: {
      marginRight: 8,
    },
    cityItemSelected: {
      backgroundColor: "#f8f9fa",
    },
    cityItemTextSelected: {
      color: "#6a5af9",
      fontWeight: "600",
    },
    noResults: {
      padding: 16,
      textAlign: "center",
      color: "#666",
      fontSize: 14,
    },
    skeletonContainer: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: "#e0e0e0",
      borderRadius: 8,
      padding: 12,
      backgroundColor: "#f5f5f5",
    },
    skeletonText: {
      height: 20,
      width: "70%",
      backgroundColor: "#e0e0e0",
      borderRadius: 4,
    },
    skeletonIcon: {
      width: 20,
      height: 20,
      backgroundColor: "#e0e0e0",
      borderRadius: 4,
    },
    iconContainer: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
    },
    calculationMethodGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    calculationMethodButton: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingVertical: 10,
      paddingHorizontal: 12,
      backgroundColor: tokens.colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: tokens.palette.gray[200],
      marginBottom: 8,
    },
    calculationMethodButtonActive: {
      backgroundColor: tokens.colors.primary,
      borderColor: tokens.colors.primary,
    },
    methodTitle: {
      fontSize: 14,
      fontWeight: "500",
      color: tokens.colors.foreground,
      marginLeft: 4,
    },
    methodTitleActive: {
      color: tokens.colors.surface,
    },
    methodDescription: {
      fontSize: 14,
      color: tokens.colors.muted,
    },
    methodDescriptionActive: {
      color: tokens.colors.surface,
    },
    methodDetailButton: {
      padding: 4,
      marginLeft: 8,
    },
    expandButton: {
      paddingVertical: 12,
      alignItems: "center",
      justifyContent: "center",
      marginTop: 0,
    },
    expandButtonText: {
      fontSize: 14,
      color: tokens.colors.primary,
      fontWeight: "500",
    },
    removeServiceItemButton: {
      position: "absolute",
      top: -8,
      right: -8,
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: "#ff3b30",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
  });
