export enum Role {
  ADMIN = 'Admin',
  OWNER = 'Owner',
  PROPERTY_MANAGER = 'Property Manager',
  ACCOUNTANT = 'Accountant',
  TENANT = 'Tenant',
}

export enum Permission {
  //Owner permissions

  // System permissions
  MANAGE_SYSTEM = 'MANAGE_SYSTEM',
  VIEW_ALL_REPORTS = 'VIEW_ALL_REPORTS',

  // Property permissions
  CREATE_PROPERTY = 'CREATE_PROPERTY',
  EDIT_PROPERTY = 'EDIT_PROPERTY',
  DELETE_PROPERTY = 'DELETE_PROPERTY',
  VIEW_PROPERTY = 'VIEW_PROPERTY',

  // Room permissions
  CREATE_ROOM = 'CREATE_ROOM',
  EDIT_ROOM = 'EDIT_ROOM',
  DELETE_ROOM = 'DELETE_ROOM',
  VIEW_ROOM = 'VIEW_ROOM',

  // Contract permissions
  CREATE_CONTRACT = 'CREATE_CONTRACT',
  EDIT_CONTRACT = 'EDIT_CONTRACT',
  DELETE_CONTRACT = 'DELETE_CONTRACT',
  VIEW_CONTRACT = 'VIEW_CONTRACT',
  TERMINATE_CONTRACT = 'TERMINATE_CONTRACT',

  // Service permissions
  CREATE_SERVICE = 'CREATE_SERVICE',
  EDIT_SERVICE = 'EDIT_SERVICE',
  DELETE_SERVICE = 'DELETE_SERVICE',
  VIEW_SERVICE = 'VIEW_SERVICE',
  RECORD_UTILITY_READING = 'RECORD_UTILITY_READING',

  // Invoice permissions
  CREATE_INVOICE = 'CREATE_INVOICE',
  EDIT_INVOICE = 'EDIT_INVOICE',
  DELETE_INVOICE = 'DELETE_INVOICE',
  VIEW_INVOICE = 'VIEW_INVOICE',
  RECORD_PAYMENT = 'RECORD_PAYMENT',

  // Maintenance permissions
  CREATE_MAINTENANCE_REQUEST = 'CREATE_MAINTENANCE_REQUEST',
  EDIT_MAINTENANCE_REQUEST = 'EDIT_MAINTENANCE_REQUEST',
  VIEW_MAINTENANCE_REQUEST = 'VIEW_MAINTENANCE_REQUEST',
  ASSIGN_MAINTENANCE_REQUEST = 'ASSIGN_MAINTENANCE_REQUEST',

  // User management permissions
  CREATE_USER = 'CREATE_USER',
  EDIT_USER = 'EDIT_USER',
  DELETE_USER = 'DELETE_USER',
  VIEW_USER = 'VIEW_USER',
  ASSIGN_ROLE = 'ASSIGN_ROLE',

  // Report permissions
  VIEW_FINANCIAL_REPORT = 'VIEW_FINANCIAL_REPORT',
  VIEW_OCCUPANCY_REPORT = 'VIEW_OCCUPANCY_REPORT',
  VIEW_DEBT_REPORT = 'VIEW_DEBT_REPORT',

  // Tenant specific permissions
  VIEW_OWN_CONTRACT = 'VIEW_OWN_CONTRACT',
  VIEW_OWN_INVOICE = 'VIEW_OWN_INVOICE',
  PAY_INVOICE = 'PAY_INVOICE',
  CREATE_OWN_MAINTENANCE_REQUEST = 'CREATE_OWN_MAINTENANCE_REQUEST',
}
