export enum ServiceCalculationMethod {
  FIXED_PER_ROOM = 'FIXED_PER_ROOM',
  FIXED_PER_PERSON = 'FIXED_PER_PERSON',
  PER_UNIT_SIMPLE = 'PER_UNIT_SIMPLE',
  PER_UNIT_TIERED = 'PER_UNIT_TIERED',
  FREE = 'FREE',
}
