import { colors } from "@/theme/colors";
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  card: {
    backgroundColor: colors.background.default,
    borderRadius: 14,
    padding: 16,
    marginBottom: 16,
    shadowColor: colors.neutral.black,
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: colors.border.light,
  },
  titleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  roomName: {
    fontSize: 17,
    fontWeight: "bold",
    color: colors.text.primary,
    flex: 1,
  },
  statusBadge: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    minWidth: 80,
    alignItems: "center",
  },
  statusText: {
    fontSize: 11,
    fontWeight: "600",
    textAlign: "center",
  },
  buildingName: {
    fontSize: 13,
    color: colors.text.secondary,
    marginBottom: 2,
  },
  price: {
    fontSize: 15,
    color: colors.primary.main,
    fontWeight: "bold",
    marginBottom: 4,
  },
  updateBtn: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: colors.primary.light,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },
  roomInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
    marginBottom: 2,
    gap: 12,
  },
  roomInfoText: {
    fontSize: 13,
    color: colors.text.secondary,
    marginRight: 8,
  },
  roomDesc: {
    fontSize: 13,
    color: colors.text.secondary,
    marginTop: 2,
    fontStyle: "italic",
  },
  contractInfo: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
  },
  contractRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  contractLabel: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  contractText: {
    fontSize: 12,
    fontWeight: "500",
    color: colors.text.primary,
  },
  paymentInfo: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border.light,
  },
  paymentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  paymentLabel: {
    fontSize: 12,
    color: colors.text.secondary,
  },
  paymentStatusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 12,
  },
  paymentStatusText: {
    fontSize: 11,
    fontWeight: "600",
  },
  paymentDateText: {
    fontSize: 12,
    fontWeight: "500",
  },
  normalText: {
    color: colors.text.secondary,
  },
  warningText: {
    color: colors.status.warning,
  },
  overdueText: {
    color: colors.status.error,
  },
  daysText: {
    fontSize: 11,
    fontStyle: "italic",
  },
  invoiceAmount: {
    fontSize: 12,
    fontWeight: "600",
    color: colors.primary.main,
  },
  actionRow: {
    flexDirection: "row",
    marginTop: 12,
    gap: 8,
  },
  createContractBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary.main,
    backgroundColor: colors.primary.light,
    gap: 4,
  },
  createContractBtnText: {
    fontSize: 12,
    color: colors.primary.main,
    fontWeight: "500",
  },
  viewContractBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary.main,
    backgroundColor: colors.primary.light,
    gap: 4,
  },
  viewContractBtnText: {
    fontSize: 12,
    color: colors.primary.main,
    fontWeight: "500",
  },
  terminateContractBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.status.error,
    backgroundColor: colors.secondary.light,
    gap: 4,
  },
  terminateContractBtnText: {
    fontSize: 12,
    color: colors.status.error,
    fontWeight: "500",
  },
  invoiceBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.primary.main,
    backgroundColor: colors.primary.light,
    gap: 4,
  },
  invoiceBtnText: {
    fontSize: 12,
    color: colors.primary.main,
    fontWeight: "500",
  },
  payBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: colors.primary.main,
    gap: 4,
  },
  payBtnText: {
    fontSize: 12,
    color: colors.neutral.white,
    fontWeight: "500",
  },
});

export default styles;
